-- MySQL Script generated by MySQL Workbench
-- vie 04 dic 2020 05:47:36 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LOGIN_AEROVUELO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LOGIN_AEROVUELO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LOGIN_AEROVUELO` ;
USE `LOGIN_AEROVUELO` ;

-- -----------------------------------------------------
-- Table `LOGIN_AEROVUELO`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOGIN_AEROVUELO`.`USUARIOS` (
  `idUSUARIOS` INT NOT NULL AUTO_INCREMENT,
  `U_NAME` VARCHAR(20) NOT NULL,
  `U_PASSWORD` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUSUARIOS`),
  UNIQUE INDEX `idUSUARIOS_UNIQUE` (`idUSUARIOS` ASC) VISIBLE,
  UNIQUE INDEX `U_PASSWORD_UNIQUE` (`U_PASSWORD` ASC) VISIBLE,
  UNIQUE INDEX `U_NAME_UNIQUE` (`U_NAME` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
