SELECT PIL.P_NOMBRE AS PILOTO, CPI.P_NOMBRE AS COPILOTO, ING.P_NOMBRE AS INGENIERO, AUX.P_NOMBRE AS AUXILIAR, PEA_VUELOS AS CODIGO_VUELO 
FROM PERSONAL PIL, PERSONAL CPI, PERSONAL ING, PERSONAL AUX, PERSONAL_EN_VUELO
WHERE PIL.idPERSONAL=PEA_idPILOTO AND CPI.idPERSONAL=PEA_idCPIL AND ING.idPERSONAL=PEA_idING AND AUX.idPERSONAL=PEA_idAUX
AND PEA_VUELOS="ALVA123";