INSERT INTO PERSONAL (idPERSONAL, P_NOMBRE, P_APELLIDO, P_idBASES) 
	VALUES (10045, "KIARA", "PONCE", "B0005");
INSERT INTO PERSONAL (idPERSONAL, P_NOMBRE, P_APELLIDO, P_idBASES) 
	VALUES (10046, "LEANDRO", "RUBIO", "B0005");
INSERT INTO PERSONAL (idPERSONAL, P_NOMBRE, P_APELLIDO, P_idBASES) 
	VALUES (10047, "ALEXANDRA", "PORTUGAL", "B0005");
INSERT INTO PERSONAL (idPERSONAL, P_NOMBRE, P_APELLIDO, P_idBASES) 
	VALUES (10048, "RICHARD", "BLANCO", "B0005");