CREATE TABLE IF NOT EXISTS USUARIOS(
  idUSUARIOS INT NOT NULL AUTO_INCREMENT,
  U_NAME VARCHAR(45) NOT NULL,
  U_USERNAME VARCHAR(20) NOT NULL,
  U_PASSWORD VARCHAR(20) NOT NULL,
  PRIMARY KEY (idUSUARIOS),
  UNIQUE INDEX `idUSUARIOS_UNIQUE` (idUSUARIOS ASC) VISIBLE,
  UNIQUE INDEX `U_PASSWORD_UNIQUE` (U_PASSWORD ASC) VISIBLE,
  UNIQUE INDEX `U_NAME_UNIQUE` (U_NAME ASC) VISIBLE,
  UNIQUE INDEX `U_USERNAME_UNIQUE` (U_USERNAME ASC) VISIBLE)
ENGINE = InnoDB;