INSERT INTO PILOTOS (idPILOTO, idPERSONAL_fk, HORAS_VOLADAS) 
	VALUES ("PI0012", 10045, 440);
INSERT INTO MIEMBROS (idMIEMBRO, idPERSONAL_fk, FUNCION) 
	VALUES ("MI0034", 10046, "COPILOTO");
INSERT INTO MIEMBROS (idMIEMBRO, idPERSONAL_fk, FUNCION) 
	VALUES ("MI0035", 10047, "INGENIERO DE VUELO");
INSERT INTO MIEMBROS (idMIEMBRO, idPERSONAL_fk, FUNCION) 
	VALUES ("MI0036", 10048,"AUXILIAR");